version: '3.4'

services:
  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trung1232003
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_userdata:/var/opt/mssql

  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=trung1
      - POSTGRES_PASSWORD=trung1
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_catalogdata:/var/lib/postgresql/data/
  
  reviewdb:
    container_name: reviewdb
    environment:
      - POSTGRES_USER=trung2
      - POSTGRES_PASSWORD=trung2
      - POSTGRES_DB=ReviewDb
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_reviewdata:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=userdb;Database=UserDb;User Id=sa;Password=Trung1232003;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - userdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  yarpapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - user.api
      - catalog.api
      - review.api
    ports:
      - "6004:8080"
      - "6064:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=trung1;Password=trung1;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  review.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=reviewdb;Port=5432;Database=ReviewDb;User Id=trung2;Password=trung2;Include Error Detail=true
    depends_on:
      - reviewdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

