version: '3.4'

services:
  userdb:
    image: mcr.microsoft.com/mssql/server

  distributedcache:
    image: redis

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

volumes:
  sqlserver_userdata:
  redis-data:
