version: '3.4'

services:
  userdb:
    container_name: userdb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trung1232003
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_userdata:/var/opt/mssql
    
  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro