version: '3.4'

services:
  userdb:
    image: mcr.microsoft.com/mssql/server

  catalogdb:
    image: postgres

  distributedcache:
    image: redis

  user.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: Services/User/User.API/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  sqlserver_userdata:
  postgres_catalogdata:
  redis-data:


